require("plote.plugins-setup")
require("plote.core.options")
require("plote.core.keymaps")
require("plote.core.colorscheme")
require("plote.plugins.comment")
require("plote.plugins.nvim-tree")
require("plote.plugins.lualine")
require("plote.plugins.telescope")
require("plote.plugins.nvim-cmp")
require("plote.plugins.lsp.mason")
require("plote.plugins.lsp.lspconfig")
require("plote.plugins.lsp.null-ls")
require("plote.plugins.lsp.trouble")
require("plote.plugins.autopairs")
require("plote.plugins.treesitter")


require("config.autocmds")
require("config.keymaps")
require("config.lazy")
require("config.options")
