require('plote.basic.colorscheme')
require('plote.basic.keymaps')
require('plote.basic.options')

require('plote.plugins.async')
require('plote.plugins.autopairs')
require('plote.plugins.comment')
require('plote.plugins.example')
require('plote.plugins.hop')
require('plote.plugins.lspsaga')
require('plote.plugins.lualine')
require('plote.plugins.nvim-cmp')
require('plote.plugins.nvim-lspconfig')
require('plote.plugins.nvim-lsp-installer')
require('plote.plugins.nvim-tree')
require('plote.plugins.setup')
require('plote.plugins.telescope')
require('plote.plugins.toggleterm')
require('plote.plugins.treesitter')

